funcScope to [] (remove self.variables to _global) & improve myTest

diff --git a/myTest b/myTest
--- a/myTest
+++ b/myTest
@@ -1,12 +1,26 @@
 #!/bin/bash
 
+EXPECTED_DIR="G"
+
+if [[ "$(basename "$(pwd)")" != "$EXPECTED_DIR" ]]; then
+    echo -e "${RED}The script must be executed in the '$EXPECTED_DIR' directory.${NC}"
+    exit 1
+fi
+
 INPUT_DIR="../tests/"
 JCONSOLE_PATH="../j9.6/bin/jconsole"
 
 EXCLUDE_FILES=(
-  "${INPUT_DIR}programa.j"            
+  "${INPUT_DIR}programa.j"
+  "${INPUT_DIR}programa2.j"            
   "${INPUT_DIR}basics/relational_op.j"
 )
+
+# Definir colores ANSI
+RED='\033[0;31m'    
+YELLOW='\033[0;33m'
+GREEN='\033[0;32m'
+NC='\033[0m'
 
 # Conver files to LF format
 echo "Converting 2 LF..."
@@ -32,24 +46,35 @@ find "$INPUT_DIR" -name "*.j" | while read -r jfile; do
     fi
 done
 echo "Done"
+echo "-----------------------------------------------------------"
 
-# Generate *.out with --test
 find "$INPUT_DIR" -name "*.j" | while read -r jfile; do
     if [[ ! " ${EXCLUDE_FILES[@]} " =~ " ${jfile} " ]]; then
-        echo "Processing mini J: $jfile"
         base_name=$(basename "$jfile" .j)
         dir_name=$(dirname "$jfile")
         input_file="${dir_name}/${base_name}.inp"
 
+        error_file="../tests/error.err"
+
         (
         . venv/bin/activate
-        python3 g.py --test "$jfile" < "$input_file"
+        python3 g.py --test "$jfile" < "$input_file" >> "$error_file" 2>&1
         )
-    else
-        echo "Skipping: $jfile"
-    fi
-done
 
+        if [[ -s "$error_file" ]]; then
+            echo -e "${RED}Error processing mini J: $jfile${NC}"
+            cat "$error_file"
+        else
+            echo -e "${GREEN}Processed mini J: $jfile${NC}"
+        fi
+        > "$error_file"
+    else
+        echo -e "${YELLOW}Skipping: $jfile${NC}"
+    fi
+
+    rm -f "$error_file"
+done
+echo "-----------------------------------------------------------"
 # Compare *.out vs *.solve, except EXCLUDE_FILES 
 find "$INPUT_DIR" -name "*.j" | while read -r jfile; do
     if [[ ! " ${EXCLUDE_FILES[@]} " =~ " ${jfile} " ]]; then
